package org.epo.dg5.utils;

public class Locators {

    public static final String SHADOW_POLICIES_FIRST = "#main-section > policy-table:nth-child(1)";
    public static final String ENVIRONMENT = "https://my-i.epo.org/user-area/mailbox-intg/";
    public static final String CERT_CLICK = "//a[@data-se='piv-card-button']";
    public static final String NATIONALITY_VALUE = "#app-container > section > section > form > section:nth-child(4) > div > div.flex-fill.p-0.m-0.pt-s.pb-s > div > div > p";
    public static final String EDIT_BUTTON = "*[data-testid='%s-section' i] *[data-testid='ModeEditIcon']";
    public static final String EDIT_FIELD_FIRSTNAME = "#firstName";
    public static final String EDIT_FIELD_LASTNAME = "#lastName";
    public static final String SECTION = "*[data-testid='%s-section' i]";
    public static final String FIELD_COUNTRY_CODE = "[aria-label='%sCountryCodeInput' i]";
    public static final String FIELD_AREA_CODE = "[aria-label='%sAreaCodeInput' i]";
    public static final String FIELD_NUMBER = "[aria-label='%sNumberInput' i]";
    public static final String FIELD_TEXT_INPUT = "*[data-testid='%s-section' i] *[aria-label='%sTextInput' i]";
    public static final String UPLOAD_FILE_BUTTON = "[class='p-button-label p-clickable']";
    public static final String DOWNLOAD_BUTTON_DOC = "//*[@data-tooltip='Herunterladen']";
    public static final String EDITION_DELETE_EVIDENCE = "[data-testid='CloseIcon']";
    public static final String INPUT_FILE = "[type='file']";
    public static final String FILE_PATH = "/home/selenium/Downloads/NAME.pdf";
    public static final String DOWNLOAD_DOCUMENT_LINK = "[data-testid='download-button']";
    public static final String FIELD_CHECKBOX_DISABLED = "[disabled]";
    public static final String OPTION_PERSONAL_INFO_CHECK = "[name='%sPersonalInfoDataProtected']";
    public static final String OPTION_ADDRESS_INFO_CHECK = "[name='%sAddressDataProtected'] i";
    public static final String OPTION_DATA_PROTECTED = "[name='%sProtectedData']";
    public static final String OPTION_DATA_PROTECTED_ITEMS = "[name='%sDataProtected']";
    public static final String ADD = "*[data-testid='%s-section' i] *[data-testid='add-%s-button' i]";
    public static final String DELETE = "*[data-testid='%s-section' i] *[data-testid='remove-%s-buttonId' i]";
    public static final String DROPDOWN_INPUT = "[data-baseweb='select']";
    public static final String DROPDOWN_FIELD = "[data-epo='epo-dropdown-single-value']";
    public static final String CANCEL_BUTTON = "[data-testid='cancel-editing-button']";
    public static final String OPTIONS_DROPDOWN_DISPLAY = "*[data-epo='epo-dropdown-option-content']";
    public static final String X_BUTTON = "[title='Clear value']";
    public static final String SUBMIT_BUTTON = "[data-testid='request-changes-button']";
    public static final String SAVE_AND_REVIEW_BUTTON = "[data-testid='stepper-action-saveAndReview']";
    public static final String ERROR_FIELD = "[aria-invalid='true']";
    public static final String CHECKBOX_NATIONALITY_FIELD = "[name='nationalOfContractingState'] *:nth-child(%s) [data-baseweb='radio']";
    public static final String REGISTRATION_NEXT_BUTTON = "[type='submit']";
    public static final String REGISTRATION_WEBSITE = "[name='webSite']";
    public static final String REGISTRATION_MAIL = "[name='email']";
    public static final String REGISTRATION_PHONE_COUNTRY_CODE = "[name='phone.countryCode']";
    public static final String REGISTRATION_PHONE_AREA_CODE = "[name='phone.areaCode']";
    public static final String REGISTRATION_PHONE_NUMBER = "[name='phone.number']";
    public static final String REGISTRATION_FAX_COUNTRY_CODE = "[name='fax.countryCode']";
    public static final String REGISTRATION_FAX_AREA_CODE = "[name='fax.areaCode']";
    public static final String REGISTRATION_FAX_NUMBER = "[name='fax.number']";
    public static final String REGISTRATION_DROPDOWNS_SELECTED = "[data-epo='epo-dropdown-value-container']";
    public static final String REGISTRATION_QUALIFIED = "[name='hasExamQualified']";
    public static final String REGISTRATION_CANCEL_REQUEST = "[data-testid='stepper-action-cancelRequest']";
    public static final String REGISTRATION_YES_CANCEL_REQUEST = "[data-theme='secondary']";
    public static final String REGISTRATION_UPLOAD_FILE = "[class='p-button p-component pi-upload-button']";
    public static final String REGISTRATION_ADDRESS = "[id='address.addressLine%s']";
    public static final String REGISTRATION_ADDRESS_CITY = "[name='address.addressCity']";
    public static final String PWB_TASK = "//*[contains(text(),'FREP: %s')]";
    public static final String PWB_TASK_NAME = "//*[contains(text(),'%s   FREP:')]";
    public static final String PWB_CLAIM = "[data-testid='claim-task-button']";
    public static final String PWB_EDIT ="[data-testid='edit-button']";
    public static final String PWB_CLEAR ="[title='Clear value']";
    public static final String PWB_CANCEL_EDIT ="[data-testid='cancel-editing-button']";
    public static final String PWB_INFO_REP ="[data-testid='RepresentativeInfoPanel']";
    public static final String PWB_RADIO ="[data-testid='radio-group']  *.undefined:nth-of-type(%s) label";
    public static final String PWB_COMMENT = "[id='comments']";
    public static final String PWB_CONFIRM = "[data-testid='confirm-task-assessments-button']";
    public static final String SPINNER = "*[data-nua='spinner']";
}
